# Generated by Django 5.1.7 on 2025-03-17 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_name', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(max_length=120)),
                ('processor', models.CharField(max_length=120)),
                ('battery', models.CharField(max_length=120)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='mobile_info.mobile_list')),
            ],
        ),
    ]
