# Generated by Django 5.1.7 on 2025-03-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile_list',
            old_name='Brand_name',
            new_name='brand_name',
        ),
        migrations.AddField(
            model_name='mobile_list',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
