# Generated by Django 5.1.6 on 2025-03-02 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies_dis',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
